config/routes.rb
Rails.application.routes.draw do
  constraints(:id => /[^\/]+/) do
    resources :stacks
    resources :resources
    resources :instances
    resources :deployments
  end
end

app/models/instance.rb
class Instance < ActiveRecord::Base
  attr_accessible :resource_id, :uuid, :deployment_id
  validates_presence_of :uuid, :resource_id, :deployment_id
  validates_uniqueness_of :uuid
  belongs_to :deployment
  belongs_to :resource

  after_destroy :remove_resource_instance

  def to_param
    uuid
  end

  private

  def remove_resource_instance
    resource.delay.destroy_instance(uuid)
  end
end

app/controllers/instances_controller.rb
class InstancesController < InheritedResources::Base
  actions :show, :index, :destroy

  protected
  def resource
    @instance ||= end_of_association_chain.find_by_uuid!(params[:id])
  end
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_form.html.erb
<%= form_for @instance do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :uuid %><br />
    <%= f.text_field :uuid %>
  </p>

  <p>
    <%= f.label :stack %><br />
    <%= f.text_field :stack %>
  </p>

  <p>
    <%= f.label :resource %><br />
    <%= f.text_field :resource %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/instances/index.html.erb
<% title "Instances" %>

<table>
  <tr>
    <th>UUID</th>
    <th>Deployment</th>
    <th>Resource</th>
    <th></th>
  </tr>
  <% for instance in @instances %>
    <tr>
      <td><%= link_to instance.uuid, instance %></td>
      <td><%= instance.deployment %></td>
      <td><%= instance.resource %></td>
      <td><%= link_to "Destroy", instance, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/instances/new.html.erb
<% title "New Instance" %>

<%= render 'form' %>

<p><%= link_to "Back to List", instances_path %></p>

app/views/instances/show.html.erb
<% title "Instance" %>

<p>
  <strong>UUID:</strong>
  <%= @instance.uuid %>
</p>
<p>
  <strong>Stack:</strong>
  <%= @instance.deployment %>
</p>

<p>
  <strong>Resource:</strong>
  <%= @instance.resource %>
</p>

<p>
  <%= link_to "Edit", edit_instance_path(@instance) %> |
  <%= link_to "Destroy", @instance, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", instances_path %>
</p>