config/routes.rb
Rails.application.routes.draw do
  constraints(:id => /[^\/]+/) do
    resources :stacks
    resources :resources
    resources :instances
    resources :deployments
  end
end

app/models/stack.rb
class Stack < ActiveRecord::Base
  attr_accessible :name, :resource_ids, :key_ids
  has_many :stack_resources, :dependent => :destroy, :conditions => {:deployment_id => nil}
  has_many :resources, :through => :stack_resources, :uniq => true
  has_many :deployments, :dependent => :destroy
  has_many :stack_keys, :dependent => :destroy
  has_many :keys, :through => :stack_keys, :dependent => :destroy
  validates_presence_of :name
  validates_uniqueness_of :name

  def to_param
    name
  end

  def to_s
    name
  end

end

app/controllers/stacks_controller.rb
class StacksController < InheritedResources::Base

  # Stack is created in two phases, this is a quick hack to avoid extra ajax calls
  def create
    create! { edit_resource_url }
    flash.clear
  end

  protected
  def resource
    @stack ||= end_of_association_chain.find_by_name!(params[:id])
  end
end

app/helpers/stacks_helper.rb
module StacksHelper
end

app/views/stacks/_form.html.erb
<%= form_for @stack do |f| %>
  <%= base_errors_for @stack %>
  <ul class="nav nav-tabs" data-tabs="tabs">
    <li class="active"><a href="#primary" data-toggle="tab"><%= _("Stack") %></a></li>
    <li><a href="#parameters" data-toggle="tab"><%= _("Parameters") %></a></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="primary">
      <%= text_f f, :name %>

      <%= multiple_checkboxes f, :resources, @stack, Resource %>
    </div>

    <div class="tab-pane" id="parameters">
      <h4> <%= _('Please select Parameters you are interested in') %></h4>
      <% @stack.resources.each do |resource| %>
        <%= multiple_checkboxes f, :keys, @stack, resource.keys, :label => resource %>
      <% end %>
    </div>
  </div>

  <%= submit_or_cancel f %>

<% end %>

app/views/stacks/edit.html.erb
<% title "Edit Stack" %>

<%= render 'form' %>

app/views/stacks/index.html.erb
<% title "Stacks" %>

<% title_actions display_link_if_authorized("New Stack", hash_for_new_stack_path), help_path %>

<table class="table table-bordered table-striped table-two-pane">
  <tr>
    <th>Name</th>
    <th>Deployments</th>
    <th>Resources</th>
    <th></th>
  </tr>
  <% @stacks.each do |stack| %>
    <tr>
      <td><%= link_to stack.name, edit_stack_path(stack) %></td>
      <td><%= stack.deployments.count %></td>
      <td><%= stack.resources.count %></td>
      <td><%= link_to "Destroy", stack, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/stacks/new.html.erb
<% title "New Stack" %>

<%= render 'form' %>

app/views/stacks/show.html.erb
<% title "Stack" %>

<h2> <%= @stack %></h2>

<pre> Add something here </pre>