config/routes.rb
Rails.application.routes.draw do
  constraints(:id => /[^\/]+/) do
    resources :stacks
    resources :resources
    resources :instances
    resources :deployments
  end
end

app/views/resources/_form.html.erb
<%= form_for @resource do |f| %>
  <%= base_errors_for @resource %>
  <%= selectable_f f, :type, Resource.subclasses.collect{|r| [r.titleize, r ] } %>

  <% if @resource.new_record? -%>
    <%= select_f f, :external_resource_id, ForemanHostgroup.list, :id, :title %>
  <% else -%>
    <%= text_f f, :name %>
  <% end -%>

  <%= submit_or_cancel f %>

<% end %>

app/views/resources/edit.html.erb
<% title "Edit Resource" %>

<%= render 'form' %>

app/views/resources/index.html.erb
<% title _("Resources") %>
<% title_actions display_link_if_authorized(_("New Resource"), hash_for_new_resource_path), help_path %>

<table class="table table-bordered table-striped table-two-pane">
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Instances</th>
    <th></th>
  </tr>
  <% for resource in @resources %>
    <tr>
      <td><%= link_to_if_authorized resource.name, hash_for_resource_path(resource) %></td>
      <td><%= resource.type.to_s.titleize %></td>
      <td><%= resource.instances.count %></td>
      <td>
        <%= action_buttons(
        link_to("Edit", edit_resource_path(resource)),

        display_delete_if_authorized(hash_for_resource_path(:id => resource), :confirm => _("Delete %s?") % resource.name))%>
      </td>
    </tr>
  <% end %>
</table>

app/views/resources/new.html.erb
<% title "New Resource" %>

<%= render 'form' %>

app/views/resources/show.html.erb
<% title "Resource" %>

<h2> <%= @resource %></h2>

<pre> Add something here </pre>